### ISSUE TITLE
Change CDN to Cloudflare

### ISSUE THREAD

**Issue by dafenix** [JakeChampion/polyfill-service-url-builder#298]
Due to latest security incident aka "supply chain attack" lets change default CDN to cloudflare.

https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know

PR: https://github.com/JakeChampion/polyfill-service-url-builder/pull/299

**Comment by JakeChampion** [comment]
fixed in v2.3.1 thank you
