### ISSUE TITLE
Security vulnerability because of Polyfill.io usage

### ISSUE THREAD

**Issue by erisnuts** [JakeChampion/polyfill-service-url-builder#300]
This package is mentioned as vulnerable in article [https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know](https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know)

**Comment by JakeChampion** [comment]
fixed in v2.3.1
